name: dienstplanenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - openpyxl
  - requests
  - pytz
  - holidays
  - bs4  # BeautifulSoup
  - pip
  - pip:
      - caldav
      - python-dateutil
